### ISSUE TITLE
Question about themes

### ISSUE THREAD

**Issue by jonashartwig** [jrop/material-ui-dialogs#1]
I see you create your own MaterialUiThemeProvider. This is run outside the context of my app i assume. Does this regard other themes?

**Comment by jrop** [comment]
No it doesn't, unfortunately.  Do you need it configurable in this way?

**Comment by jonashartwig** [comment]
Yes, but as the button texts are hard wired as well and the content I assume we will build something on your work. I do like the idea behind it though and it works nicely!

**Comment by jrop** [comment]
@jonashartwig If you submit a PR, I would consider merging it.

**Comment by jonashartwig** [comment]
ok.
