### ISSUE TITLE
Redux-form

### ISSUE THREAD

**Issue by oallouch** [jrop/material-ui-dialogs#2]
Hi,
I've make a cleanup of an old version of your code and made a redux-form wrapper component that allows the usage of await with a redux-form, returning the values (or null).
Are you interested in adding it to your repo ?

Olivier (from Paris)

**Comment by jrop** [comment]
Glad you found this useful!  This repo is mostly specific to `material-ui` and I think if I incorporated `redux-forms` it would be beyond the scope of this project.  You are welcome to create another module for redux-forms, though.  I'd be interested in seeing the finished product, please link it here when you are done!

**Comment by oallouch** [comment]
Hi,
I've just updated my repo so that you can see how I changed it in a more API way. I think it's more appropriate that using components. Also check the 'action' property in action buttons.
Concerning the redux-form part, a component makes sense because we need the store (in the context).
https://github.com/oallouch/material-ui-dialogs
Tell me what you think about it.
Thx in advance.

Olivier

**Comment by jrop** [comment]
Hi @oallouch, my initial feeling on this is that this does not really add much to what just using `material-ui` already gives you.  This should likely be its own module.  The goal of my module was to mimic `window.{alert,confirm,prompt}(..)` behavior with a promise API.  I think your additions go well beyond that, and should likely be their own module.

**Comment by oallouch** [comment]
I understand, but the thing I wanted you to check is the alternate design of the core lib.
Anyway, thanks for your time and the initial code.
I'll find a new name, but add a link to your initial repo.
Thx again

**Comment by jrop** [comment]
@oallouch Do you mean the way the parameters changed?  My thought on that is right now, the API follows how `window.alert`, `window.prompt`, and `window.confirm` work, which will be familiar to most users.  I would like to keep them as close to that as possible.  Thanks!

**Comment by oallouch** [comment]
Ah ok. I prefer adding options like "okLabel". And I like the fact the its more API-centric . Looks at the size of the code of "confirm". It looks normal that all the deferred thing is handled once, in one function.
