### ISSUE TITLE
please check this closed issue

### ISSUE THREAD

**Issue by oallouch** [jrop/material-ui-dialogs#3]
Hi,
I don't know if you missed my comment (because the issue is closed).
But please take a look at https://github.com/jrop/material-ui-dialogs/issues/2

Thx,
Olivier

**Comment by jrop** [comment]
@oallouch Thank you!  I will try to look soon; I am a little short on time today, but will try to remember to check this in a day or two.

**Comment by jrop** [comment]
@oallouch replied in the other issue, closing this one
