### ISSUE TITLE
How to close alert dialog without click on "okay" button - Urgent

### ISSUE THREAD

**Issue by divyanshupathak** [jrop/material-ui-dialogs#5]
Hi,
In my app, I am using this alert dialog. I want to close the alert dialog by pressing back button of Android device instead of click on OKAY button in the dialog. Is it possible or not? If yes, Please suggest me the solution for this requirement. **It's urgent for my app.**
Thanks

**Comment by jrop** [comment]
You can probably accomplish this task with this library, but I would not recommend it.  This library is meant to emulate `window.alert`/`window.prompt`/`window.confirm` as closely as possible.  It sounds like you may just want to use `material-ui/Dialog` directly (without this wrapper).  (If you are intent on using this library we can figure something out, however)

**Comment by divyanshupathak** [comment]
Yes, definitely I like this library and want to go further with it in my app. Can you please suggest me the solution?

**Comment by jrop** [comment]
@divyanshupathak Have a look at how this is implemented in the library.  Everything you should need is exported:

https://github.com/jrop/material-ui-dialogs/blob/master/src/index.js#L94

**Comment by jrop** [comment]
@divyanshupathak Can this issue be closed?

**Comment by divyanshupathak94** [comment]
yes
